version: '2'

services:

  demo-db:
    image: "mysql:8.0.19"
    ports:
      - "32811:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    container_name: template
    volumes:
      - template-data:/var/lib/mysql

  demo-test-db:
    image: "mysql:8.0.19"
    ports:
      - "32812:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    container_name: template-tests
    volumes:
      - template-test-data:/var/lib/mysql

volumes:
  template-data:
  template-test-data: